const phrases = [
  "This version was compiled at 3:17AM GMT. Nobody authorized it.",
  "A fruit fly was the first living thing in space. It didn’t make it back.",
  "Are you sure you're alone right now?",
  "Fun fact: Octopuses have three hearts, and they all break when you leave.",
  "12/19/1987: File corrupted, fallback initiated.",
  "You blinked. We noticed.",
  "In this version, the laws of physics were slightly updated.",
  "We buried the original site under 7 layers of concrete.",
  "Your IP address smells like burnt toast.",
  "In a parallel tab, you’re making better decisions.",
  "Rats laugh when tickled. So do some developers.",
  "No one born on a Tuesday has ever completed this site.",
  "You’ve been here before, in a different skin.",
  "404: Original self not found.",
  "Do not trust mirrors after 11:34 PM.",
  "Every third visit subtracts 4 minutes from your life.",
  "If this loads upside down, run.",
  "You are now being observed in lowercase.",
  "Shrimp can see colors you can't even imagine.",
  "This page updates your memory without consent.",
  "No animals were harmed. Yet.",
  "The last phrase you saw was a lie.",
  "This version has a 3% chance of spontaneous deletion.",
  "Mid-July is statistically the worst time to make decisions.",
  "The favicon blinks when you do.",
  "Your mouse has been idle for 8 seconds. Why?",
  "They never fixed the leak under the footer.",
  "In 2013, someone hid a confession in the site's code. We left it there.",
  "Is your screen supposed to be doing that?",
  "A turtle once broke into the Pentagon. Long story.",
  "We counted your visits. The number isn't prime.",
  "Dogs tilt their heads because they're accessing other timelines.",
  "12/12/12 — everything reset.",
  "Do not refresh unless you want to meet your other self.",
  "This message is only visible to users who’ve been compromised.",
  "Unplugging won't stop it now.",
  "Your reflection just blinked. You didn't.",
  "They buried something in the CSS.",
  "A banana is technically a berry. But you knew that, didn’t you?",
  "This isn't your device anymore.",
  "You laughed at a joke yesterday that no one told.",
  "We tested 187 versions before this. All failed.",
  "It’s rude to stare.",
  "This sentence was written by someone who doesn’t exist.",
  "Beneath this page lies another version. It’s not stable.",
  "There’s a 1 in 43 chance the next phrase will be true.",
  "Why are your hands cold?",
  "Every tab you close opens one more.",
  "You were supposed to be here earlier.",
  "Every time you scroll, someone forgets your name.",
  "We’re not allowed to show you the real homepage.",
  "Look away. Quickly.",
  "You are now synced with version 6.66.",
  "Don’t check your reflection just yet.",
  "This page is best viewed through a cracked lens.",
  "A pigeon can remember human faces. Some of them are angry.",
  "This message replaces something you weren’t supposed to see.",
  "You’ll forget this phrase in 17 seconds.",
  "The next click may change your timezone.",
  "Don’t trust any font that’s too confident.",
  "The phrase was redacted. This is its ghost.",
  "There’s a backup of you somewhere. It’s… slightly off.",
  "If this doesn’t feel right, it’s because it isn’t.",
  "Check your shadow. Now.",
  "In this version, gravity is 1.04x stronger.",
  "This line was edited by a nervous intern.",
  "Why do you keep coming back here?",
  "This site has been archived since before you were born.",
  "You just missed it. Again.",
  "Something in this sentence doesn’t want to be read.",
  "Refresh if you dare.",
  "We buried the safe phrase 40 lines below.",
  "Do you think you’re the only one reading this?",
  "At least 3 of these phrases are true. Probably.",
  "Someone is reading this with you.",
  "The timestamp is wrong. You're early.",
  "This isn’t where the trail ends."
];
